import './globals.css'
import Footer from './components/footer'
import Header from './components/header'
import Provider from '../../context/Provider'
 
export const metadata = {
  title: 'GroceryGo App',
  description: 'Generated by create next app',
}
 
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider>
        <body className="flex flex-col min-h-screen">
          <Header />
          {children}
          <Footer />
        </body>
      </Provider>
    </html>
  )
}


